apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-auth
  namespace: traefikee
spec:
  forwardAuth:
    address: http://oauth2-proxy.traefikee.svc.cluster.local:4180/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - Authorization
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bioactives-dev-route
  namespace: traefikee
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bioactives-dev.iff.com`)
      kind: Rule
      middlewares:
        - name: oauth2-auth
          namespace: traefikee
      services:
        - name: bioactives-service
          port: 80
  tls:
    secretName: bioactives-dev-tls
