apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: traefikee
data:
  oauth2_proxy.cfg: |
    provider = "azure"
    client_id = "0efee129-77a4-4d23-8a96-e256d34da134"
    azure_tenant = "a2a9bf31-fc44-425c-a6d2-3ae9379573ea"
    email_domains = ["*"]
    cookie_secure = true
    cookie_domains = ["bioactives-dev.iff.com"]
    whitelist_domains = ["bioactives-dev.iff.com"]
    redirect_url = "https://bioactives-dev.iff.com/oauth2/callback"
    upstreams = ["file:///dev/null"]
    pass_access_token = true
    pass_authorization_header = true
    pass_user_headers = true
    set_authorization_header = true
    set_xauthrequest = true
    standard_logging = true
    auth_logging = true
    request_logging = true
    skip_provider_button = true
    ssl_insecure_skip_verify = true
    silence_ping_logging = true
