apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: traefikee
data:
  OAUTH2_PROXY_REDIRECT_URL: "https://bioactives-dev.iff.com/oauth2/callback"
  OAUTH2_PROXY_COOKIE_NAME: "_oauth2_proxy"
  OAUTH2_PROXY_COOKIE_DOMAINS: ".iff.com"
  OAUTH2_PROXY_WHITELIST_DOMAINS: ".iff.com"
  OAUTH2_PROXY_AZURE_TENANT: "common"
  OAUTH2_PROXY_SCOPE: "openid email profile"
  OAUTH2_PROXY_SESSION_STORE_TYPE: "cookie"
  OAUTH2_PROXY_SESSION_COOKIE_MINIMAL: "true"
  OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "false"
  OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY: "false"
  OAUTH2_PROXY_PASS_BASIC_AUTH: "true"
  OAUTH2_PROXY_PASS_USER_HEADERS: "true"
  OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
