apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: traefikee
data:
  oauth2_proxy.cfg: |
    provider = "azure"
    email_domains = ["*"]
    cookie_secure = true
    cookie_domains = ["bioactives-dev.iff.com"]
    whitelist_domains = [".bioactives-dev.iff.com"]
    redirect_url = "https://bioactives-dev.iff.com/oauth2/callback"
