apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: traefikee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
        ports:
        - containerPort: 4180
          protocol: TCP
        args:
        - --provider=azure
        - --azure-tenant=
        - --email-domain=*
        - --upstream=static://200
        - --http-address=0.0.0.0:4180
        - --cookie-secure=true
        - --cookie-samesite=lax
        - --reverse-proxy=true
        - --set-xauthrequest=true
        - --pass-access-token=true
        - --pass-authorization-header=true
        - --pass-user-headers=true
        - --skip-provider-button=true
        envFrom:
        - configMapRef:
            name: oauth2-proxy-config
        - secretRef:
            name: oauth2-proxy-secret
        readinessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: traefikee
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: oauth2-proxy
