apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: traefikee
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: "${OAUTH2_PROXY_CLIENT_ID}"
  OAUTH2_PROXY_CLIENT_SECRET: "${OAUTH2_PROXY_CLIENT_SECRET}"
  OAUTH2_PROXY_COOKIE_SECRET: "${OAUTH2_PROXY_COOKIE_SECRET}"
  OAUTH2_PROXY_AZURE_TENANT: "${OAUTH2_PROXY_AZURE_TENANT}"
