apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: traefikee
type: Opaque
stringData:
  # Microsoft Entra ID credentials
  OAUTH2_PROXY_CLIENT_ID: "replace-with-client-id"
  OAUTH2_PROXY_CLIENT_SECRET: "replace-with-client-secret"

  # Cookie secret (must be 32 characters long)
  OAUTH2_PROXY_COOKIE_SECRET: "replace-with-32-char-random-string"

  # Azure tenant ID
  OAUTH2_PROXY_AZURE_TENANT: "replace-with-tenant-id"
