apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: traefikee
type: Opaque
data:
  cookie_secret: ${COOKIE_SECRET}  # Will be replaced during deployment
  client_secret: ${CLIENT_SECRET}  # Will be replaced during deployment
